### ISSUE TITLE
No need for manual static asset handling -- use "getPublicUrl"

### ISSUE THREAD

**Issue by sjc5** [jaymanmdev/pokemon-roundest-with-htmx#1]
Anywhere in your server source code, you can do:

```tsx
import { getPublicUrl } from "hwy";

const url = getPublicUrl("relative-path-to-file-in-public-dir");
```

For example, if you have an asset at `~/public/some-asset.jpg`, you can reference that as `getPublicUrl("some-asset.jpg")`, and it will be hashed, immutably cached, have appropriate headers added, and served.

Nice work on this, looking great @jaymanmdev!

**Comment by jaymanmdev** [comment]
@sjc5 Do you have an example using `getPublicUrl` with font faces?

What I am doing is creating a font face like so in `tw-input.css`:
```css
@font-face {
  font-family: "Geist";
  font-display: swap;
  src: url(/fonts/geist.woff2) format("woff2");
}
```

I'm going to need to use the public url in here as well. Is the best way forward to just inline a style tag into the document with the injected content or is there a better way out? I'd like for this font face to be cached etc if possible.

Thanks!
